language: ruby
script: bundle exec rake test
bundler_args: --without development docs
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - rbx-2
jdk:
  - openjdk7
env:
  global:
    - FAIL_FAST=N
  matrix:
    - VM_NUMBER=1 CASSANDRA_VERSION=2.0.9
    - VM_NUMBER=2 CASSANDRA_VERSION=2.0.9
    - VM_NUMBER=3 CASSANDRA_VERSION=2.0.9
    - VM_NUMBER=4 CASSANDRA_VERSION=2.0.9
    - VM_NUMBER=5 CASSANDRA_VERSION=2.0.9
    - VM_NUMBER=1 CASSANDRA_VERSION=1.2.18
    - VM_NUMBER=2 CASSANDRA_VERSION=1.2.18
    - VM_NUMBER=3 CASSANDRA_VERSION=1.2.18
    - VM_NUMBER=4 CASSANDRA_VERSION=1.2.18
    - VM_NUMBER=5 CASSANDRA_VERSION=1.2.18
matrix:
  exclude:
    - rvm: 1.9.3
      env: VM_NUMBER=2 CASSANDRA_VERSION=2.0.9
    - rvm: 1.9.3
      env: VM_NUMBER=3 CASSANDRA_VERSION=2.0.9
    - rvm: 1.9.3
      env: VM_NUMBER=4 CASSANDRA_VERSION=2.0.9
    - rvm: 1.9.3
      env: VM_NUMBER=5 CASSANDRA_VERSION=2.0.9
    - rvm: 1.9.3
      env: VM_NUMBER=2 CASSANDRA_VERSION=1.2.18
    - rvm: 1.9.3
      env: VM_NUMBER=3 CASSANDRA_VERSION=1.2.18
    - rvm: 1.9.3
      env: VM_NUMBER=4 CASSANDRA_VERSION=1.2.18
    - rvm: 1.9.3
      env: VM_NUMBER=5 CASSANDRA_VERSION=1.2.18
    - rvm: 2.0.0
      env: VM_NUMBER=1 CASSANDRA_VERSION=2.0.9
    - rvm: 2.0.0
      env: VM_NUMBER=3 CASSANDRA_VERSION=2.0.9
    - rvm: 2.0.0
      env: VM_NUMBER=4 CASSANDRA_VERSION=2.0.9
    - rvm: 2.0.0
      env: VM_NUMBER=5 CASSANDRA_VERSION=2.0.9
    - rvm: 2.0.0
      env: VM_NUMBER=1 CASSANDRA_VERSION=1.2.18
    - rvm: 2.0.0
      env: VM_NUMBER=3 CASSANDRA_VERSION=1.2.18
    - rvm: 2.0.0
      env: VM_NUMBER=4 CASSANDRA_VERSION=1.2.18
    - rvm: 2.0.0
      env: VM_NUMBER=5 CASSANDRA_VERSION=1.2.18
    - rvm: 2.1.1
      env: VM_NUMBER=1 CASSANDRA_VERSION=2.0.9
    - rvm: 2.1.1
      env: VM_NUMBER=2 CASSANDRA_VERSION=2.0.9
    - rvm: 2.1.1
      env: VM_NUMBER=4 CASSANDRA_VERSION=2.0.9
    - rvm: 2.1.1
      env: VM_NUMBER=5 CASSANDRA_VERSION=2.0.9
    - rvm: 2.1.1
      env: VM_NUMBER=1 CASSANDRA_VERSION=1.2.18
    - rvm: 2.1.1
      env: VM_NUMBER=2 CASSANDRA_VERSION=1.2.18
    - rvm: 2.1.1
      env: VM_NUMBER=4 CASSANDRA_VERSION=1.2.18
    - rvm: 2.1.1
      env: VM_NUMBER=5 CASSANDRA_VERSION=1.2.18
    - rvm: jruby
      env: VM_NUMBER=1 CASSANDRA_VERSION=2.0.9
    - rvm: jruby
      env: VM_NUMBER=2 CASSANDRA_VERSION=2.0.9
    - rvm: jruby
      env: VM_NUMBER=3 CASSANDRA_VERSION=2.0.9
    - rvm: jruby
      env: VM_NUMBER=5 CASSANDRA_VERSION=2.0.9
    - rvm: jruby
      env: VM_NUMBER=1 CASSANDRA_VERSION=1.2.18
    - rvm: jruby
      env: VM_NUMBER=2 CASSANDRA_VERSION=1.2.18
    - rvm: jruby
      env: VM_NUMBER=3 CASSANDRA_VERSION=1.2.18
    - rvm: jruby
      env: VM_NUMBER=5 CASSANDRA_VERSION=1.2.18
    - rvm: rbx-2
      env: VM_NUMBER=1 CASSANDRA_VERSION=2.0.9
    - rvm: rbx-2
      env: VM_NUMBER=2 CASSANDRA_VERSION=2.0.9
    - rvm: rbx-2
      env: VM_NUMBER=3 CASSANDRA_VERSION=2.0.9
    - rvm: rbx-2
      env: VM_NUMBER=4 CASSANDRA_VERSION=2.0.9
    - rvm: rbx-2
      env: VM_NUMBER=1 CASSANDRA_VERSION=1.2.18
    - rvm: rbx-2
      env: VM_NUMBER=2 CASSANDRA_VERSION=1.2.18
    - rvm: rbx-2
      env: VM_NUMBER=3 CASSANDRA_VERSION=1.2.18
    - rvm: rbx-2
      env: VM_NUMBER=4 CASSANDRA_VERSION=1.2.18
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "o2spP9TWvr/r41zcddtskpgTuU9SSJxkourYe9Sjx07OcQulAXT7TbZIFwpPvCUfB5uBLKq4vrSWthG3EcCCxFH2etzmTtnPInybbVyDFjwOd/aAF4JHhXGvqoO+QZ/3CSPtHukUZX96hryy8ko46Trxeue8FtWMQYnIFSXMdWc="
  on:
    tags: true
