language: ruby
script: bundle exec rake test
bundler_args: --without development docs
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - rbx-2
jdk:
  - openjdk7
env:
  global:
    - FAIL_FAST=no
    - COVERAGE=no
  matrix:
    - CASSANDRA_VERSION=2.0.9
    - CASSANDRA_VERSION=1.2.18
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "o2spP9TWvr/r41zcddtskpgTuU9SSJxkourYe9Sjx07OcQulAXT7TbZIFwpPvCUfB5uBLKq4vrSWthG3EcCCxFH2etzmTtnPInybbVyDFjwOd/aAF4JHhXGvqoO+QZ/3CSPtHukUZX96hryy8ko46Trxeue8FtWMQYnIFSXMdWc="
  on:
    tags: true
