language: ruby
script: bundle exec rake rspec
bundler_args: --without development docs
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby
  - rbx-2.2.10
env:
  global:
    - FAIL_FAST=no
    - COVERAGE=no
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
branches:
  only:
    - master
