language: ruby
script: bundle exec rake test
bundler_args: --without development docs
before_install:
  - pip install ccm
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - jruby-head
  - rbx-2
jdk:
  - openjdk7
env:
  global:
    - FAIL_FAST=N
  matrix:
    - CASSANDRA_VERSION=2.0.9
    - CASSANDRA_VERSION=1.2.18
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
