language: ruby
script: bundle exec rake test
bundler_args: --without development docs
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - cd support/ccm
  - python setup.py install
  - cd -
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby
  - rbx
jdk:
  - openjdk7
env:
  global:
    - FAIL_FAST=no
    - COVERAGE=no
  matrix:
    - CASSANDRA_VERSION=2.1.2
    - CASSANDRA_VERSION=2.0.12
    - CASSANDRA_VERSION=1.2.19
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
branches:
  only:
    - master
