ruby:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2.2
os:
  - ubuntu/trusty64
env:
  CASSANDRA_VERSION:
    - 1.2.19
    - 2.0.16
    - 2.1.9
    - 2.2.1
build:
  - type: bundler
    without: development docs
  - script: |
      bundle exec rake test
